### PR TITLE
Group + Noti + Job Center Edit

### PR DESCRIPTION
**Pull request by Q4D1952K**

### CODE REVIEW

**Comment by FjamZoo** [comment]
You seem to be having some conflicts if u can fix those

**Comment by Iitsmemitchell** [comment]
This would be an awesome fix!

**Comment by paruthepro** [comment]
client/groups.lua:148:53: unused argument 'data'

client/groups.lua:148:59: unused argument 'cb'

client/jobcenter.lua:4:9: unused loop variable 'k'

client/jobcenter.lua:11:51: unused argument 'data'

server/groups.lua:101:21: line contains trailing whitespace

^^^ Fix these issues and it can be merged 👍

**Comment by itsKline** [comment]
Unfixed issues after months, PR closed

**Pull request closed without merging**
