### PR TITLE
Gang App 1.0.0

### PR DESCRIPTION
**Pull request by Swompen**
An easy app for gangs, to hire, change roles and kick people from gangs. Im shit at UI so some stuff are probably crap but it works as a initial release.

Test it and see if i fucked it somewhere, come with suggestions to add or change.

image

### CODE REVIEW

**Comment by Swompen** [comment]
> Screenshot_6

I manually moved the code over to be able to PR it, cuz my phone is way to remade, and i forgot to add in some stuff in main for gangs..

Pushed now.

**Comment by KrnkTV** [comment]
This app make conflict with employment app when install this one back arrow i to employement app stop working

**Comment by paruthepro** [comment]
Yup, there's conflicts with the jobs app, rewrite it otherwise it won't be pulled.

**Comment by itsKline** [comment]
Too many conflicting issues to be pulled

**Pull request closed without merging**
