### PR TITLE
Adding 2 group job exports

### PR DESCRIPTION
**Pull request by zf-development**
- updateJobStage (change the state of a specific stage without updating all stages)
- getJobStage (get the last done stage)

### CODE REVIEW

**Comment by paruthepro** [comment]
remove the unused argument on line 176 of groups.lua then should be good :)

**Comment by zf-development** [comment]
@paruthepro Done. ✅

**Comment by paruthepro** [comment]
Should be sorted for merge then, just gotta wait for them :)

**Comment by zf-development** [comment]
@paruthepro Is this going to be Merged? 3 weeks ago you said that it should be sorted for merge... Still not merged...

**Pull request closed without merging**
