### PR TITLE
Walking & Driving with phone out

### PR DESCRIPTION
**Pull request by Swompen**
Changes made to main.lua and two js files.

When phone is out you can still move and drive etc, as soon as you select a text field those controls will stop so you dont punch or do random crap.

### CODE REVIEW

**Comment by ChainedDev** [comment]
If possible, you should make this Config based, as some people may now want their players to be able to use phone while doing all of that stuff

**Comment by ChainedDev** [comment]
Also should check out the new qb-exports

exports['qb-smallresources']:addDisableControls({})

exports['qb-smallresources']:removeDisableControls({})

instead of making your own loop

**Comment by MannyOnBrazzers** [comment]
I agree with both above ^

**Comment by MannyOnBrazzers** [comment]
Will add an update utilizing the newer exports

**Pull request merged**
